# Generated by Django 3.0.4 on 2020-05-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luminosity', '0002_luminosity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='luminosity',
            name='latitude',
            field=models.IntegerField(default=0, verbose_name='latitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='luminosity',
            name='lenght',
            field=models.IntegerField(default=0, verbose_name='longitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='luminosity',
            name='terrain',
            field=models.CharField(default='Sin terreno', max_length=20, verbose_name='Terreno'),
            preserve_default=False,
        ),
    ]
